### PR TITLE
Update 01/08/2020

### PR DESCRIPTION
**Pull request by Ollieollieolllie**
Cscope container fix & ECM script rework

### CODE REVIEW

**Comment by mattysmith22** [comment]
This is great progress, well done! I would just like to make one request before we merge it in:

When you are just using the IHADSS, not in the TADS, you can see targets in the C-scope outside of the monocle which isn't physically possible with the real aircraft. Maybe you could use [`cameraView`](https://community.bistudio.com/wiki/cameraView) to work out whether they are in the camera or not, and if the latter restrict which ones are viewable?

**Comment by SachaOropeza** [comment]
Is this ready for review and merge guys ?

**Comment by mattysmith22** [comment]
I would still like my aforementioned upgrade to be implemented before it is merged, otherwise you will be able to see C-scope targets even when they are outside of the monocle area

**Comment by SachaOropeza** [comment]
No worries brother. I’ll wait for your approval to merge. ✌️

**Review by SachaOropeza — COMMENTED** [review]
Waiting for Matty's approval for merge.

**Review by SachaOropeza — APPROVED** [review]
CBA release being close enough, I'm pushing this on master.

**Comment by SachaOropeza** [comment]
@Ollieollieolllie Many errors in CfgFunctions that I had to fix. Please check your files. Missing semicolon and input after EndofFile. Fixed on my end.

**Pull request merged**
